# https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/external-admin-secret-credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  default_user.conf: |
    default_user = test
    default_pass = 123qweASD
  host: rabbitmq.rabbitmq.svc
  username: test
  password: 123qweASD
  port: "5672"
  provider: rabbitmq
  type: rabbitmq